version: '3.8'

services:
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./node1.conf:/etc/redis/redis.conf

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./node2.conf:/etc/redis/redis.conf

  redis-node-3:
    image: redis:7-alpine
    container_name: redis-node-3
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./node3.conf:/etc/redis/redis.conf